### ISSUE TITLE
KeyError: "There is no item named 'vocab.txt' in the archive"

### ISSUE THREAD

**Issue by birlikov** [ltgoslo/simple_elmo#6]
Thanks for great work! 
I have downloaded 170-model from [NLPL word embeddings repository](http://vectors.nlpl.eu/repository/#) (Russian CoNLL17 corpus, ELMo) - it does not have `vocab.txt` in it and `KeyError: "There is no item named 'vocab.txt' in the archive"` occurred when trying to load it into the model, but I thought it was optional as described in docs. Any hints how to resolve?
```~/.pyenv/versions/3.7.3/lib/python3.7/site-packages/simple_elmo/elmo_helpers.py in load(self, directory, top, max_batch_size, limit)
     64                 )
     65             zf = zipfile.ZipFile(directory)
---> 66             vocab_file = zf.open("vocab.txt")
     67             options_file = zf.open("options.json")
     68             weight_file = zf.open("model.hdf5")

~/.pyenv/versions/3.7.3/lib/python3.7/zipfile.py in open(self, name, mode, pwd, force_zip64)
   1465         else:
   1466             # Get info object for name
-> 1467             zinfo = self.getinfo(name)
   1468 
   1469         if mode == 'w':

~/.pyenv/versions/3.7.3/lib/python3.7/zipfile.py in getinfo(self, name)
   1393         if info is None:
   1394             raise KeyError(
-> 1395                 'There is no item named %r in the archive' % name)
   1396 
   1397         return info

KeyError: "There is no item named 'vocab.txt' in the archive"```

**Comment by akutuzov** [comment]
This is a model trained by the ElmoForManyLangs project. These models were trained using a different flavor of ELMo code, yielding a different architecture. Therefore, _simple_elmo_ cannot work with these models. See our [FAQ](https://github.com/ltgoslo/simple_elmo#can-i-load-elmoformanylangs-models) for more details. Essentially, all ELMo models from the NLPL vector repository trained on CONLL17 corpora are like this. Note that these models are not useful for anything except syntax anyway, since they are trained on very small samples of CONLL17 corpora (20 mln tokens or so).

Any other ELMo models trained with the original architecture can still be loaded, whatever is their source. For Russian, we recommend http://vectors.nlpl.eu/repository/20/199.zip and http://vectors.nlpl.eu/repository/20/212.zip
